name: Playwright Tests with Reqnroll

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Playwright Reqnroll Tests
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup the .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # 3. Install Reqnroll.Nunit and other dependencies
    - name: Install Dependencies
      run: |

        # cd PlaywrightReqnrollFramework
        # dotnet add package Reqnroll.NUnit --version 2.4.1
        # dotnet add package Microsoft.Playwright.NUnit --version 1.52.0
        # dotnet add package Microsoft.Playwright --version 1.52.0
        dotnet restore
    
    #4. Buld the project
    - name: Build the project (required before install)
      run: dotnet build    
   
    #5. Install Playwright browsers
    - name: Install Playwright browsers
      run: |
            dotnet tool run playwright install

    # 6. Run tests with NUnit console logger
    - name: Run Tests
      run: dotnet test --no-build --logger "console;verbosity=normal" --logger "nunit;LogFilePath=TestResults/TestResults.xml"

    # 7. Upload test results (optional)
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          TestResults/
          
