name: Playwright Tests with Reqnroll (NUnit3 + ExtentReports)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests (NUnit3)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore and Build
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
      
      - name: Restore .NET tools
        run: dotnet tool restore    

      - name: Install Playwright
        run: dotnet playwright install

      - name: Run Tests (NUnit3)
        run: |
          dotnet test --no-build --configuration Release --logger:"nunit;LogFilePath=TestResults/nunit-results.xml"
          ls -R TestResults
        shell: pwsh

      - name: Upload NUnit Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nunit-test-results
          path: PlaywrightReqnrollFramework/TestResults/nunit-results.xml

      - name: Publish ExtentReports
        if: always()
        run: |
          if (Test-Path TestResults/ExtentReports) {
            Compress-Archive -Path TestResults/ExtentReports/* -DestinationPath extent-reports.zip -Force
            ls -R TestResults/ExtentReports
          }
        shell: pwsh
      - name: Locate extent-reports.zip
        run: Get-ChildItem -Recurse -File -Filter extent-reports.zip
        shell: pwsh
      - name: Upload ExtentReports
        uses: actions/upload-artifact@v4
        with:
          name: extent-reports
          path: |
            extent-reports.zip
            PlaywrightReqnrollFramework/TestResults/ExtentReports/*.html
            PlaywrightReqnrollFramework/TestResults/Screenshots/*.png
