name: List All Files

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List all files recursively
        run: Get-ChildItem -Recurse -File