name: List All Files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  list-files:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests
        run: dotnet test --no-build --logger "nunit;LogFilePath=TestResults/TestResults.xml"

      - name: List all files recursively
        run: Get-ChildItem -Recurse -File